// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfRJEF3ZghglyGQ_CTDMsE5LOx5V-hp6c',
    appId: '1:60560488809:web:6f3db83782be817b5b65f8',
    messagingSenderId: '60560488809',
    projectId: 'babysit-f347e',
    authDomain: 'babysit-f347e.firebaseapp.com',
    storageBucket: 'babysit-f347e.appspot.com',
    measurementId: 'G-58N37XFXWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArEi8OGt_lNpemWbKXvzNQf-G0d78t90A',
    appId: '1:60560488809:android:764da2250b251c755b65f8',
    messagingSenderId: '60560488809',
    projectId: 'babysit-f347e',
    storageBucket: 'babysit-f347e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpcuhc5sERHQbxM9fo0D_a99RbsChnyVQ',
    appId: '1:60560488809:ios:606500e926ac86dd5b65f8',
    messagingSenderId: '60560488809',
    projectId: 'babysit-f347e',
    storageBucket: 'babysit-f347e.appspot.com',
    iosBundleId: 'com.example.babysit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpcuhc5sERHQbxM9fo0D_a99RbsChnyVQ',
    appId: '1:60560488809:ios:606500e926ac86dd5b65f8',
    messagingSenderId: '60560488809',
    projectId: 'babysit-f347e',
    storageBucket: 'babysit-f347e.appspot.com',
    iosBundleId: 'com.example.babysit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfRJEF3ZghglyGQ_CTDMsE5LOx5V-hp6c',
    appId: '1:60560488809:web:4ff386b94c1ef22d5b65f8',
    messagingSenderId: '60560488809',
    projectId: 'babysit-f347e',
    authDomain: 'babysit-f347e.firebaseapp.com',
    storageBucket: 'babysit-f347e.appspot.com',
    measurementId: 'G-W2LYWXMJRR',
  );
}
